version: '2'
services:
    truequep-app:
        image: truequep
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://truequep-postgresql:5432/truequep
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    truequep-postgresql:
        extends:
            file: postgresql.yml
            service: truequep-postgresql
